### ISSUE TITLE
Указать, что Б.1 относится к организаторам рейтингуемых турниров, а не только синхронных

### ISSUE THREAD

**Issue by gltronred** [maii-chgk/documents#16]
Сейчас [так](https://www.maii.li/p/aegis-rating#b1):

> Организаторы синхронных турниров должны соблюдать [требования](https://rating.chgk.info/documents.php?doc=55) [Турнирного сайта](https://www.maii.li/p/aegis-rating#turnir-site) по отношению к формату и содержанию вносимых данных].

Но эти же требования должны относиться и к очным турнирам, поэтому стоит заменить слово "синхронных" на "рейтингуемых"

**Comment by nfarukshin** [comment]
То есть ты думаешь, что это лучше вынести в требования рейтингуемых турниров (п. 2.2.4)?

**Comment by gltronred** [comment]
В [2.2.4.6.2](https://www.maii.li/p/aegis-rating#22462) уже есть требование вносить результаты и составы. Получается, суть Б.1 в том, что нужно соблюдать формат данных турнирного сайта. Не знаю, насколько это нужно вносить в основной текст

**Comment by nfarukshin** [comment]
То есть просто убрать, и оставить расписание ок?

**Comment by gltronred** [comment]
Кажется, можно просто убрать

**Comment by nfarukshin** [comment]
Я ещё немного подумал и всё-таки оставил этот пункт. В 2.2.1 как будто всё же рамочные требования указаны, а в приложении Б иные.

Лучше действительно, как ты сформулировал в изначальном запросе, не акцентироваться на «синхронных». И заодно добавить что-то из [этого ишью](https://github.com/maii-chgk/documents/issues/28).

**Comment by nfarukshin** [comment]
Вот в каком-то таком виде.

<a name="b2"></a> **Б.2.** При проведении турнира организаторы обязаны соблюдать указанные ниже крайние сроки. Также организаторы могут установить более короткие сроки по своему усмотрению.

<table class="uk-table uk-table-divider uk-table-hover">
<thead>
  <tr>
  <th></th>
  <th>Синхронные</th>
  <th>Строго синхронные</th>
  <th>Очные</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>Внесение составов, результатов и спорных</td>
    <td>X + 3</td>
    <td>X + 3</td>
    <td>X + 7</td>
  </tr>
    <tr>
    <td>Публикация вердиктов ИЖ</td>
    <td>X + 6</td>
    <td> - </td>
    <td> - </td>
  </tr>
  <tr>
    <td>Подача апелляций</td>
    <td>X + 9</td>
    <td> - </td>
    <td> - </td>
  </tr>
  <tr>
    <td>Открытие результатов</td>
    <td>X + 14</td>
    <td>X + 14</td>
    <td> - </td>
  </tr>
  <tr>
    <td>Публикация вердиктов АЖ</td>
    <td>X + 16</td>
    <td> - </td>
    <td> - </td>
  </tr>
    <tr>
    <td>Внесение исправлений</td>
    <td>X + 19</td>
    <td> - </td>
    <td> - </td>
  </tr>
    <tr>
    <td>Открытие результатов</td>
    <td>X + 20</td>
    <td>X + 7</td>
    <td>X + 7</td>
  </tr>
</tbody>

<small>«X» в таблице обозначает момент завершения отыгрыша турнира. Числа везде указывают на количество суток.</small>

**Comment by gltronred** [comment]
В таком виде, кстати, от очников требуется внесение спорных. Это, конечно, хорошо, но неудобно, вряд ли будет соблюдаться

**Comment by gltronred** [comment]
И ещё два раза повторяется "Открытие результатов". Второй раз, наверное, что-то другое должно быть ("Подведение итогов турнира"?)

**Comment by nfarukshin** [comment]
Поправил, теперь так:

<a name="b2"></a> **Б.2.** При проведении турнира организаторы обязаны соблюдать указанные ниже крайние сроки. Также организаторы могут установить более короткие сроки по своему усмотрению.

<table class="uk-table uk-table-divider uk-table-hover">
<thead>
  <tr>
  <th></th>
  <th>Синхронные</th>
  <th>Строго синхронные</th>
  <th>Очные</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>Внесение составов и результатов</td>
    <td>X + 3</td>
    <td>X + 3</td>
    <td>X + 7</td>
  </tr>
  <tr>
    <td>Внесение спорных</td>
    <td>X + 3</td>
    <td>X + 3</td>
    <td> - </td>
  </tr>
    <tr>
    <td>Публикация вердиктов ИЖ</td>
    <td>X + 6</td>
    <td> - </td>
    <td> - </td>
  </tr>
  <tr>
    <td>Подача апелляций</td>
    <td>X + 9</td>
    <td> - </td>
    <td> - </td>
  </tr>
  <tr>
    <td>Открытие результатов</td>
    <td>X + 14</td>
    <td>X + 14</td>
    <td> - </td>
  </tr>
  <tr>
    <td>Публикация вердиктов АЖ</td>
    <td>X + 16</td>
    <td> - </td>
    <td> - </td>
  </tr>
    <tr>
    <td>Внесение исправлений</td>
    <td>X + 19</td>
    <td> - </td>
    <td> - </td>
  </tr>
    <tr>
    <td>Итоги становятся окончательными</td>
    <td>X + 20</td>
    <td>X + 7</td>
    <td>X + 7</td>
  </tr>
</tbody>

«X» в таблице обозначает момент завершения отыгрыша турнира. Числа везде указывают на количество суток.
