### ISSUE TITLE
Проверить, актуальна ли инфа о выходе релизов рейтинга

### ISSUE THREAD

**Issue by nfarukshin** [maii-chgk/documents#20]
Вроде было какое-то расхождение

**Comment by nfarukshin** [comment]
Текущая формулировка такая: 

А.2.1. Релизы Рейтинга выпускаются каждый четверг в 23:59 UTC+3. Если в промежуток от четверга до четверга не было ни одного рейтингуемого турнира, релиз не выпускается. На границе сезонов выпускаются два релиза — в последний четверг августа и в пятницу, следующую за ним. Все релизы в момент выпуска получают статус предварительного релиза (пререлиза) и фиксируются через три недели.

@razumau можешь, пожалуйста, проверить, соответствует ли эта формулировка текущей ситуации. А если нет, то как ещё лучше поправить?

**Comment by razumau** [comment]
Всё из этого неправда.

> Релизы Рейтинга выпускаются каждый четверг в 23:59 UTC+3.

Не очень понятно, что это значит — мы пересчитываем каждые несколько часов. Расчёт достаточно близко к 23:59 тоже есть, конечно, но ничем не отличается от других.

> Если в промежуток от четверга до четверга не было ни одного рейтингуемого турнира, релиз не выпускается.

Выпускается (такого никогда не бывает, впрочем).

> На границе сезонов выпускаются два релиза — в последний четверг августа и в пятницу, следующую за ним.

Не выпускаются, сейчас у нас есть только релизы каждый четверг.

> Все релизы в момент выпуска получают статус предварительного релиза (пререлиза) и фиксируются через три недели.

Тоже не очень ясно, что это значит: если результаты старых турниров меняются, бонусы за них изменятся (мы постоянно пересчитываем все релизы от сентября 2021 года) — было бы странно это не делать. Концепция официального релиза не кажется полезной: если организаторы турнира отбирают по рейтингу, они сами фиксируют, в какой момент и на какой релиз они посмотрят.

**Comment by nfarukshin** [comment]
То есть в итоге у нас остаётся из всего этого только так? (мне либо ты, либо Егор говорили про три часа). Или что-то ещё надо добавить для понимания ситуации?

А.2.1. Релизы Рейтинга выпускаются каждые три часа. 

Также нужно ли изменить ограничение про пятницу из пункта ниже (и попросить турнирный сайт пофиксить все эти ограничения), учитывая, что релизы у нас постоянно практически считаются? В какой момент у нас игрок может попадать в БС в этом случае?

> А.1.6. Формирование и дополнение БС через турниры может производиться в течение всего сезона (с учётом правила [А.1.3](https://www.maii.li/p/aegis-rating#a13)). **Датой внесения игрока в базовый состав считается последняя пятница перед днём релиза, в котором учтён этот турнир.** Исключение: игрока нельзя внести в БС через многоэтапный турнир, результаты которого вносятся после его завершения.

**Comment by gltronred** [comment]
> Не очень понятно, что это значит — мы пересчитываем каждые несколько часов

К какому моменту относится релиз, который в выпадающем списке релизов?
Или, точнее - до какого момента времени турнир будет относится к этому релизу?

**Comment by gltronred** [comment]
> Концепция официального релиза не кажется полезной: если организаторы турнира отбирают по рейтингу, они сами фиксируют, в какой момент и на какой релиз они посмотрят.

Кажется, есть отличие между (пре)релизами, в которых турниры с нерассмотренными спорными-апелляциями, и релизами, изменения в которых могут произойти только из-за нештатных ситуаций (решения ДГ и ТГ). 

Упомянуть это отличие стоит, чтобы организаторы брали не самый свежий релиз (как интуитивно хочется), а тот, в котором результаты не изменятся в результате обычного хода проведения турнира. Хотя бы в виде рекомендации или комментария, если не хочется вводить новую терминологию

**Comment by nfarukshin** [comment]
>Упомянуть это отличие стоит, чтобы организаторы брали не самый свежий релиз (как интуитивно хочется), а тот, в котором результаты не изменятся в результате обычного хода проведения турнира.

А как ты один от другого отличишь? Синхроны же накладываются друг на друга.

**Comment by razumau** [comment]
> Датой внесения игрока в базовый состав считается последняя пятница перед днём релиза, в котором учтён этот турнир.

Это по сути так и есть, хоть и без явной пятницы в коде: если дата внесения в состав меньше или равна дате релиза, мы учитываем игрока как базового в турнирах этого релиза.

**Comment by razumau** [comment]
Три часа я бы точно никуда не вносил: это случайное число, и к нему незачем привязываться (я хочу переделать то, как мы запускаем все обновления и расчёты, можно выбрать числа получше, но при этом я свежие релизы обсчитывал бы, возможно, чаще, а старые — реже).

Давайте начнём не с того, что в доке или в коде, а с того, как мы хотели бы видеть и называть релизы.

**Comment by nfarukshin** [comment]
>Это по сути так и есть, хоть и без явной пятницы в коде: если дата внесения в состав меньше или равна дате релиза, мы учитываем игрока как базового в турнирах этого релиза.

То есть что-то в таком духе?

> А.1.6. Через турниры БС может формирваться и дополняться в течение всего сезона (с учётом правила [А.1.3](https://www.maii.li/p/aegis-rating#a13)). Игрок учитывается в базовом составе со следующего релиза (или обновления, прим. НФ) рейтинга. Исключение: игрока нельзя внести в БС через многоэтапный турнир, результаты которого вносятся после его завершения.

**Comment by nfarukshin** [comment]
>Давайте начнём не с того, что в доке или в коде, а с того, как мы хотели бы видеть и называть релизы.

Не совсем понимаю. Ты считаешь, что «релиз» плохо объясняет, что происходит? Про «видеть» вообще не понял :(

**Comment by gltronred** [comment]
> А как ты один от другого отличишь? Синхроны же накладываются друг на друга.

У каждого синхрона есть релиз, к которому он относится (первый после даты завершения отыгрыша). Для каждого релиза есть дата, когда при нормальном течении событий будут подведены итоги синхронов, входящих в релиз (три недели после выхода релиза)

Возможно, я не понял вопроса

**Comment by nfarukshin** [comment]
Или я не понял, для чего организаторам брать какой-то релиз. В моём понимании организаторы «берут» релиз в одном случае — при объявлении заявок на фестиваль говорят «мол, сразу берём топ-10 команд в рейтинге на такое-то число». Я не понял, причём тут конкретный релиз для конкретного синхрона.

Или у тебя есть другие сценарии, при котором это нужно?

**Comment by gltronred** [comment]
> при объявлении заявок на фестиваль говорят «мол, сразу берём топ-10 команд в рейтинге на такое-то число»

Да, я про этот сценарий, но тут есть нюанс. Сравни две ситуации. Допустим, организаторы говорят: 4 ноября утром мы посмотрим на сайт и возьмём топ-10 команд в релизе от ...:
- 3 ноября;
- 6 октября.

В первой ситуации часть результатов не будет учтена (например, не введены полностью турниры с завершением 1 ноября), и топ-10 может поменяться. Мне кажется, так делать не надо. 

Во второй - результаты всех турниров, учтённых в этом релизе, введены, спорные и апелляции рассмотрены. На мой взгляд, такой вариант более справедливо отбирает топ-10.

**Comment by nfarukshin** [comment]
Тебе не кажется, что это скорее вопрос того, насколько организаторы понимают, как считается рейтинг? Просто я не понимаю, как описание у нас поможет в данном случае.
