### ISSUE TITLE
Апелляции: чётче прописать требования

### ISSUE THREAD

**Issue by nfarukshin** [maii-chgk/documents#22]
Чтобы организаторы не могли мухлевать так, чтобы нельзя было не подавать апелляции.

Текущая формулировка:
2.2.4.4. Регламент турнира должен предусматривать подачу апелляций. В апелляционном жюри турнира должно быть не менее трёх человек. В апелляционное жюри турнира не могут входить редакторы или авторы вопросов турнира.

**Comment by nfarukshin** [comment]
Пример: ершов выставляет сроки приёма апелляций так, чтобы их невозможно было подать (https://rating.chgk.info/tournament/9285).

**Comment by nfarukshin** [comment]
Например, так.

2.2.4.4.1. Оргкомитет должен обеспечить участникам турнира возможность подавать апелляции на зачёт ответа и на некорректность вопроса в соответствии со сроками, указанными в этом Положении.
2.2.4.4.2. В апелляционном жюри турнира должно быть не менее трёх человек. В в него не могут входить редакторы или авторы вопросов турнира.

**Comment by gltronred** [comment]
> В в него не могут входить редакторы или авторы вопросов турнира.

Лишняя "в", должно быть: "В него не могут входить редакторы или авторы вопросов турнира"

**Comment by nfarukshin** [comment]
>Лишняя "в", должно быть
отредачил

>Обязательно ли оба этих типа? Кажется, было достаточно зачёта ответа (но не уверен)

Можно предложить на голосование два варианта: оба типа или только зачёт.
