### ISSUE TITLE
Удалить дублирующийся пункт об отзыве из-за грубого нарушения правил игры

### ISSUE THREAD

**Issue by nfarukshin** [maii-chgk/documents#26]
Пункт 1.3.2.2.6 дублирует пункт 1.3.2.2.1

1.3.2.2.6. Также эгида может быть отозвана в иных случаях, которые [ТГ](https://www.maii.li/p/aegis-rating#tg) посчитает грубым нарушением правил той игры, по которой проводится турнир.

1.3.2.2. Отзыв эгиды может быть связан со следующими нарушениями:
1.3.2.2.1. Грубое нарушение правил игры, по которой проводится турнир.

**Comment by gltronred** [comment]
Предлагаешь объединить? 

1.3.2.2.1. Грубое нарушение правил игры, по которой проводится турнир. Определение грубости нарушения проводится ТГ

**Comment by nfarukshin** [comment]
Не совсем: предлагаю оставить только 1.3.2.2.1, потому что выше и так написано, что эгида отзывается либо по заявлению оргов, либо решением ТГ, дублировать ещё раз про решение ТГ вроде нет смысла особого.

**Comment by nfarukshin** [comment]
Удалил пункт в ветке aegis-rating-forth-edition
