### ISSUE TITLE
Сроки ввода результатов очных и строго синхронных турниров

### ISSUE THREAD

**Issue by gltronred** [maii-chgk/documents#28]
Сейчас сроки ввода составов и результатов в [Б.2](https://www.maii.li/p/aegis-rating#b2) относятся только к синхронных турнирам.

Предлагается добавить п.Б.3 для очных и строго синхронных турниров в следующем виде:

> Б.3. Организаторы очных и строго синхронных турниров обязаны соблюдать следующие временные рамки при проведении:
> X: завершение отыгрыша турнира;
> X+72 часа (3 суток): крайний срок внесения на Турнирный сайт информации о составах и результатах;
> X+336 часов (14 суток): крайний срок открытия суммарных результатов турнира (без разбиения на отдельные вопросы и туры);
> X+336 часов (14 суток): итоги турнира становятся окончательными.
> При этом оргкомитет может установить более короткие сроки по своему усмотрению.

**Comment by nfarukshin** [comment]
Я бы тут первую настройку сделал бы всё же 7 суток, трое кажется жестковато.

А в чем смысл второй штуки, ведь у очников такого нет, а строго-синхронные не закрывают результатов... Кстати, может просто вынести эту настройку на уровень выше, и сделать её обязательной для всех рейтинговых турниров, чтобы не повторяться с синхроными?

Третью я тоже не понимаю, что значит «становятся окончательными»? Типа даже ошибки нельзя поправить или что?

**Comment by gltronred** [comment]
> Я бы тут первую настройку сделал бы всё же 7 суток, трое кажется жестковато.

Я просто взял из Б.2. Можно спросить оргов очников, каким лучше сделать конкретное значение.
 
> А в чем смысл второй штуки, ведь у очников такого нет, а строго-синхронные не закрывают результатов... Кстати, может просто вынести эту настройку на уровень выше, и сделать её обязательной для всех рейтинговых турниров, чтобы не повторяться с синхроными?

Насколько я помню, смысл этой настройки для синхронов был в том, чтобы открыть достаточно результатов для расчёта рейтинга, но не слишком много, чтобы не дать читерам возможности оценивать требуемое количество взятий. Кажется, что для очников и их зеркал должна быть такая же логика (хотя лично мне она кажется слишком параноидальной).

> Третью я тоже не понимаю, что значит «становятся окончательными»? Типа даже ошибки нельзя поправить или что?

Да, все ошибки исправлены до этого момента, можно учитывать в рейтинге, дальше только какие-то форс-мажорные обстоятельства могут повлиять на итоги.

**Comment by nfarukshin** [comment]
>Можно спросить оргов очников

А как ты это собираешься делать? Не в чате же «спортивные интеллектуальные игры»)

>Насколько я помню, смысл этой настройки для синхронов был в том, чтобы открыть достаточно результатов для расчёта рейтинга, но не слишком много, чтобы не дать читерам возможности оценивать требуемое количество взятий. Кажется, что для очников и их зеркал должна быть такая же логика

Про синхроны я понимаю, я о том, что на очниках у тебя просто нет настройки закрыть результаты. А на строгих синхронах их никто и не закрывает... Короче с одной стороны это логично, а с другой странно.

В общем и целом я бы просто вынес штуку про открытие результатов просто вместо удалённого Б.1, раз она актуальна почти для всех турниров.
