### ISSUE TITLE
Убрать из Положения ЭР пункт А. 1.5

### ISSUE THREAD

**Issue by nfarukshin** [maii-chgk/documents#5]
А.1.5. Команда, преемственная одновременно к нескольким БС, считается преемственной той команде, название которой она использует; при отсутствии такого названия не считается преемственной ни к какой команде.

**Comment by nfarukshin** [comment]
Можно также заменить на такое (это происходит фактически):

А.1.5. Команда, преемственная одновременно к нескольким БС, считается преемственной той команде, ID которой она использует.

**Comment by gltronred** [comment]
Согласен, в [А.3.3.1](https://www.maii.li/p/aegis-rating#a331), где про составы на турнирах, уже так указано

**Comment by nfarukshin** [comment]
А, отл, тогда точно удаляем просто.
