### ISSUE TITLE
Добавить расшифровку ЭГ в п.0 Положения об эгиде и рейтинге

### ISSUE THREAD

**Issue by gltronred** [maii-chgk/documents#8]
В [разделе 3](https://github.com/maii-chgk/documents/blob/main/aegis-rating.ru.md#3-%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F-%D0%B2-%D0%BF%D0%BE%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B8-) Положения об эгиде и рейтинге, возможно, будет использоваться аббревиатура ЭГ (после голосования 6 января).

Нужно её расшифровать в начале Положения.

**Comment by gltronred** [comment]
@nfarukshin можно в #9 добавить

**Comment by nfarukshin** [comment]
Я там сделал временную заглушку, было лень думать (см. в третьем разделе, где якорь #eg). Можешь придумать определение для электронного голосования, тогда добавим в «Термины и определения»?

**Comment by gltronred** [comment]
Как в п.4.2.9 устава, "электронное голосование членов МАИИ, проводимое без созыва ОС"?

**Comment by nfarukshin** [comment]
Можно так, но это не суперпонятно, кажется. Впрочем, хз, как сделать понятнее :(

Если делать так, то на ОС нужно поставить ссылку
